Update r.yml

diff --git a/.github/workflows/r.yml b/.github/workflows/r.yml
--- a/.github/workflows/r.yml
+++ b/.github/workflows/r.yml
@@ -47,6 +47,17 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Import data
+        run: Rscript -e 'source("scripts/file_test.R")'
+
+      - name: Commit results
+        run: |
+          git config --local user.email "actions@github.com"
+          git config --local user.name "GitHub Actions"
+          git add Errors preventing latest commit.csv
+          git commit -am 'Error file updated' || echo "No change to error file"
+          git push origin main || echo "No changes to commit"
+
+      - name: Import data
         run: Rscript -e 'source("scripts/3a_update_all_files.R")'
 
       - name: Commit results
